# Generated by Django 2.0.7 on 2018-07-05 16:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('moved', 'moved'), ('added', 'added')], max_length=25)),
                ('modified', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('added_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_user', to=settings.AUTH_USER_MODEL)),
                ('board_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Board')),
                ('from_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_list', to='boards.Column')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
