# Generated by Django 2.0.7 on 2018-07-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20180706_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('moved', 'moved'), ('added', 'added'), ('on', 'on'), ('archived', 'archived')], max_length=25),
        ),
    ]
