# Generated by Django 2.0.6 on 2018-07-12 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_cardcomment_archived'),
        ('activity', '0002_auto_20180712_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='board',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='boards.Board'),
            preserve_default=False,
        ),
    ]
