# Generated by Django 2.0.7 on 2018-07-10 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20180710_1811'),
        ('activity', '0003_auto_20180710_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='boards.Card'),
        ),
        migrations.AddField(
            model_name='activity',
            name='second_action',
            field=models.CharField(blank=True, choices=[('moved', 'moved'), ('added', 'added'), ('on', 'on'), ('archived', 'archived')], max_length=25, null=True),
        ),
    ]
