# Generated by Django 2.0.7 on 2018-07-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20180711_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('moved', 'moved'), ('added', 'added'), ('on', 'on'), ('archived', 'archived'), ('to', 'to')], max_length=25),
        ),
        migrations.AlterField(
            model_name='activity',
            name='second_action',
            field=models.CharField(blank=True, choices=[('moved', 'moved'), ('added', 'added'), ('on', 'on'), ('archived', 'archived'), ('to', 'to')], max_length=25, null=True),
        ),
    ]
