# Generated by Django 2.0.7 on 2018-07-10 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20180710_1811'),
        ('activity', '0005_auto_20180711_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='to_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_card', to='boards.Card'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('moved', 'moved'), ('added', 'added'), ('on', 'on'), ('archived', 'archived'), ('to', 'to'), ('updated', 'updated')], max_length=25),
        ),
        migrations.AlterField(
            model_name='activity',
            name='second_action',
            field=models.CharField(blank=True, choices=[('moved', 'moved'), ('added', 'added'), ('on', 'on'), ('archived', 'archived'), ('to', 'to'), ('updated', 'updated')], max_length=25, null=True),
        ),
    ]
