# Generated by Django 2.0.6 on 2018-07-11 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20180710_1811'),
        ('activity', '0006_auto_20180711_0143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='card',
            new_name='first_card',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='board_name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='from_list',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='second_action',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='to_card',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='to_list',
        ),
        migrations.AddField(
            model_name='activity',
            name='first_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_list', to='boards.Column'),
        ),
        migrations.AddField(
            model_name='activity',
            name='second_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_list', to='boards.Column'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('added_list', 'added_list'), ('update_list', 'update_list'), ('archived_list', 'archived_list'), ('added_card', 'added_card'), ('updated_card_title', 'updated_card_title'), ('updated_card_description', 'updated_card_description'), ('add_comment', 'add_comment'), ('deleted_comment', 'deleted_comment'), ('transferred_card', 'transferred_card'), ('assign_member', 'assign_member')], max_length=25),
        ),
        migrations.AlterField(
            model_name='activity',
            name='added_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='added_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
