# Generated by Django 2.0.6 on 2018-07-11 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20180710_1811'),
        ('activity', '0007_auto_20180711_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='board',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='boards.Board'),
            preserve_default=False,
        ),
    ]
