# Generated by Django 2.0.6 on 2018-07-11 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_activity_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='added_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
