# Generated by Django 2.0.6 on 2018-07-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
