# Generated by Django 2.0.6 on 2018-07-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmember',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
