# Generated by Django 2.0.6 on 2018-07-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_card_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
