# Generated by Django 2.0.6 on 2018-07-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_cardcomment_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
