# Generated by Django 2.0.6 on 2018-07-06 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0006_auto_20180706_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(null=True)),
                ('due_date', models.DateTimeField(null=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Board')),
            ],
        ),
        migrations.CreateModel(
            name='CardComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cardcomments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='column',
        ),
        migrations.AlterField(
            model_name='cardmember',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Card'),
        ),
        migrations.DeleteModel(
            name='CardComments',
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
    ]
