# Generated by Django 2.0.6 on 2018-07-08 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_card_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcomment',
            name='date_commented',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
